### PR TITLE
Added Ability to drop events from cron scheldule

### PR DESCRIPTION
**Pull request by butuzov**

### CODE REVIEW

**Comment by jrfnl** [comment]
Ready for some feedback ?

**Comment by butuzov** [comment]
Rool it out.

**Comment by jrfnl** [comment]
I haven't tested it yet - will do in a moment, but looking at the code, there are some things I'd suggest:

1. As - once the plugin is activated - it will load on every page, I would advocate for having a js file containing the code in `footer_js()` and using [wp_localize_script](https://codex.wordpress.org/Function_Reference/wp_localize_script) to pass through the three variables you need. This will allow browsers to cache the js rather than having it write it to every page. This also means we can serve a minified js file.
For an example of how to do this: https://github.com/jrfnl/Debug-Bar-Shortcodes/blob/master/class-debug-bar-shortcodes.php#L65-L102 in combination with https://github.com/jrfnl/Debug-Bar-Shortcodes/blob/master/js/debug-bar-shortcodes.js
2. In the js call - the removal of the cron job *might* fail. You now remove the table row from the page on success, but give no feedback when the removal fails.
3. Consider using the native WP `maybe_serialize()` and `maybe_unserialize()`.
4. Escape all output - HTML attributes should be escaped with `esc_attr()`, translated strings with `esc_html()` or using `esc_html__()` (translate + escape in one go), urls using `esc_url()`, etc.
5. I'd need to check on the risks, but you may also want to have a look at some additional input validation of the via ajax received variables before passing them on.

Also there are a number of coding style issues too - not to worry though, let's leave those till last & see if they still need solving or if the code has changed beyond that by then.

**Comment by butuzov** [comment]
thanks.

1) Did it before, so know how to do it. Just a personal preference to have a short js code on every page,   instead a separate files (and need to maintain them) (Specially if we compare output with output of almost any debug module). Will fix - however, due it make general sense.
2)  Make sense as for me. I will change it a bit later.
3) OK.
4) OK.
5) OK.

**Comment by butuzov** [comment]
Will back with refreshed version.

**Pull request closed without merging**
