### PR TITLE
Few improvements for next version

### PR DESCRIPTION
**Pull request by butuzov**
-  Added functionality to delete ( unscheldule ) cron-event while you viewing a events array
-  View for events changed to hold events in few rows if they happening same-time.
-  bugfix - Correct cron events number in "Total Events"

### CODE REVIEW

**Comment by jrfnl** [comment]
Hi @butuzov Would you mind refreshing this PR so I can test it with the current code base ? Thanks!

**Comment by butuzov** [comment]
Hi @jrfnl. Sorry i am not reallys ure what i need to do (I  am still bit new to github). afaics, only ajax - actions removal not in changes that you have implement... Should i merge a code and try to create new pull request?

**Comment by jrfnl** [comment]
Hi @butuzov Thanks for your response.
No worries about being new to github, we all were at some point. I'm happy to help/teach you if you like.

It really is only about the delete option. I believe I caught the other issues already and fixes those.

You could either apply these changes again to the current master and create a new pull request or alternatively you can update this pull request by adding additional merges - or preferably - by doing a `rebase`.

For a clean merge history, a rebase is the neater way to update a PR. Similarly - for future reference -, if you are working on several different changes, you can create different branches for each change. That way, each change can be tested in isolation and evaluated individually.

Please let me know if I need more explanation. I'm happy to help you.

**Comment by butuzov** [comment]
Thanks for explanations.  I will delete repo, add changes till the end of the day, and create a new pull request.  I will implement only cron events remove feature (due it only one left important). Is it ok?

**Comment by jrfnl** [comment]
Sounds good to me! Thanks.

**Comment by jrfnl** [comment]
Hi @butuzov I was just wondering how you were getting on with creating the new version of your PR... Hope all is well and wish you a great new year.

**Comment by butuzov** [comment]
I am really sorry for a huge delay I did. Can you take a look to the code before I create a pull request ?
here is updated code. https://github.com/butuzov/debug-bar-cron/commit/d8168cb479e6e330b8d7bfb8c01c6fc8defb1baf

Thank you.

**Comment by jrfnl** [comment]
@butuzov Not to worry, glad to hear from you. I'll try and take a look some time over the next few days when I have a moment.

**Comment by butuzov** [comment]
Thank you Juliet.

**Comment by jrfnl** [comment]
@butuzov I'm really sorry that it's taken me so long before getting round to this.
I'll be reviewing your code this weekend & will add my feedback to the commit.

**Comment by jrfnl** [comment]
@butuzov Ok, code review done. Sorry about the mountain of remarks. Hope you'll find my feedback useful.

**Comment by jrfnl** [comment]
@butuzov Just wondering what the current status is ...

**Comment by butuzov** [comment]
Dear @jrfnl 
I beg for pardon once again. Updates are pushed to repository. i will comment them in few moments.

**Comment by butuzov** [comment]
@jrfnl Did you have chance to see updates? (I am reallys orry for previous delayes)...

**Comment by jrfnl** [comment]
Sorry, been very busy with other things, will try to have a look next week.

**Comment by jrfnl** [comment]
@butuzov Just checking - where can I find the latest status to review ? In this PR or elsewhere ?

**Comment by butuzov** [comment]
Hi. 
Thanks for your time.

here is your last comments regarding "whats wrong" -> https://github.com/butuzov/wp-debug-bar-cron/commit/30d5e7ba0132fba431776624639c8a0ad62761b2
and the all code -> https://github.com/butuzov/wp-debug-bar-cron/commits/feature/remove-schelduled-event

**Comment by butuzov** [comment]
Hi Juliet is it too late to ask how it's going? No plans for merging my code?

**Pull request closed without merging**
